#!/bin/bash
set -eux


mkdir -p /etc/cloud/cloud.cfg.d
cat > /etc/cloud/cloud.cfg.d/90-network-manager-renderer.cfg <<'EOF'
# This file ensures cloud-init prefers NetworkManager for network rendering
system_info:
  network:
    renderers: ['network-manager', 'sysconfig', 'eni', 'netplan', 'networkd']
EOF
chmod 0644 /etc/cloud/cloud.cfg.d/90-network-manager-renderer.cfg
