ARG EDPM_BASE_IMAGE
FROM $EDPM_BASE_IMAGE

ARG PACKAGES="\
    bind-utils \
    buildah \
    cephadm \
    chrony \
    cloud-init \
    cronie \
    crudini \
    crypto-policies-scripts \
    device-mapper-multipath \
    driverctl \
    growvols \
    grubby \
    iproute-tc \
    iptables-services \
    iscsi-initiator-utils \
    jq \
    lvm2 \
    nftables \
    numactl \
    openssh-server \
    openstack-network-scripts \
    openstack-selinux \
    openvswitch \
    os-net-config \
    podman \
    python3-libselinux \
    python3-pyyaml \
    rsync \
    tmpwatch \
    tuned-profiles-cpu-partitioning \
    sysstat \
    yum-utils \
    "
ARG ENABLE_UNITS="openvswitch"

ARG LIBVIRT_PACKAGES="\
    libvirt \
    libvirt-admin \
    libvirt-client \
    libvirt-daemon \
    qemu-kvm \
    qemu-img \
    libseccomp \
    swtpm \
    swtpm-tools \
    edk2-ovmf \
    ceph-common \
    cyrus-sasl-scram \
    "

ARG RHSM_SCRIPT=empty.sh
COPY $RHSM_SCRIPT /var/tmp/rhsm-script.sh
RUN /var/tmp/rhsm-script.sh && \
    dnf -y install $PACKAGES $LIBVIRT_PACKAGES && \
    dnf clean all && \
    (subscription-manager remove --all || true) && \
    (subscription-manager unregister || true) && \
    systemctl enable $ENABLE_UNITS

# Drop Ansible fact into place
COPY ansible-facts/bootc.fact /etc/ansible/facts.d/bootc.fact
RUN chmod +x /etc/ansible/facts.d/bootc.fact

# Disable automatic update check and reboot
RUN systemctl mask bootc-fetch-apply-updates.timer

# This should be the last command
# https://docs.fedoraproject.org/en-US/bootc/building-containers/#_linting
RUN bootc container lint
