ARG EDPM_BASE_IMAGE
FROM $EDPM_BASE_IMAGE

# edpm_bootstrap
ARG BOOTSTRAP_PACKAGES="\
    driverctl \
    lvm2 \
    crudini \
    jq \
    nftables \
    NetworkManager \
    openstack-selinux \
    python3-libselinux \
    python3-pyyaml \
    rsync \
    tmpwatch \
    sysstat \
    iproute-tc \
    ksmtuned \
    systemd-container \
    crypto-policies-scripts \
    grubby \
    openstack-network-scripts \
    "

# dib/ceph packages
ARG CEPH_PACKAGES="\
    bind-utils \
    cephadm \
    "

# edpm_growvols
ARG GROWVOLS_PACKAGES="\
    growvols \
    "

# edpm_logrotate_crond
ARG LOGROTATE_CROND_PACKAGES="\
    cronie \
    "
# edpm_network_config
ARG NETWORK_CONFIG_PACKAGES="\
    os-net-config \
    NetworkManager-ovs \
    "

# edpm_ovs
ARG OVS_PACKAGES="\
    openvswitch \
    "

# edpm_podman
ARG PODMAN_PACKAGES="\
    buildah \
    podman \
    "

# edpm_reboot
ARG REBOOT_PACKAGES="\
    yum-utils \
    "

# edpm_sshd
ARG SSHD_PACKAGES="\
    openssh-server \
    "

# edpm_tuned
ARG TUNED_PACKAGES="\
    tuned \
    tuned-profiles-cpu-partitioning \
    "

ARG PACKAGES="\
    chrony \
    cloud-init \
    device-mapper-multipath \
    iptables-services \
    iscsi-initiator-utils \
    numactl \
    "
ARG ENABLE_UNITS="openvswitch"

ARG LIBVIRT_PACKAGES="\
    libvirt \
    libvirt-admin \
    libvirt-client \
    libvirt-daemon \
    qemu-kvm \
    qemu-img \
    libseccomp \
    swtpm \
    swtpm-tools \
    edk2-ovmf \
    ceph-common \
    cyrus-sasl-scram \
    "

ARG TELEMETRY_LOGGING_PACKAGES="\
    rsyslog-openssl
    "

ARG RHSM_SCRIPT=empty.sh
COPY $RHSM_SCRIPT /var/tmp/rhsm-script.sh
RUN /var/tmp/rhsm-script.sh && \
    dnf -y install \
        $BOOTSTRAP_PACKAGES \
        $CEPH_PACKAGES \
        $GROWVOLS_PACKAGES \
        $PACKAGES \
        $LIBVIRT_PACKAGES \
        $LOGROTATE_CROND_PACKAGES \
        $NETWORK_CONFIG_PACKAGES \
        $OVS_PACKAGES \
        $PODMAN_PACKAGES \
        $REBOOT_PACKAGES \
        $SSHD_PACKAGES \
        $TUNED_PACKAGES \
        $TELEMETRY_LOGGING_PACKAGES && \
    # edpm_bootstrap
    source /etc/os-release && if [ "${ID}" = "rhel" ]; then dnf -y install rhoso-release; fi && \
    # edpm_kernel
    dnf -y remove dracut-config-generic && \
    dnf clean all && \
    (subscription-manager remove --all || true) && \
    (subscription-manager unregister || true) && \
    systemctl enable $ENABLE_UNITS

# Drop Ansible fact into place
COPY ansible-facts/bootc.fact /etc/ansible/facts.d/bootc.fact
RUN chmod +x /etc/ansible/facts.d/bootc.fact

# Disable automatic update check and reboot
RUN systemctl mask bootc-fetch-apply-updates.timer

# This should be the last command
# https://docs.fedoraproject.org/en-US/bootc/building-containers/#_linting
RUN bootc container lint
